<?php

declare(strict_types=1);

/**
 * Bootstraps the theme and wires together setup, front-end assets, and editor assets.
 */

if (! defined('ABSPATH')) {
    exit;
}

const D11_VERSION = '0.1.0';

require_once get_theme_file_path('inc/assets.php');
require_once get_theme_file_path('inc/blocks.php');
require_once get_theme_file_path('inc/patterns.php');

foreach (glob(get_theme_file_path('partials/*.php')) ?: [] as $partial_file) {
    require_once $partial_file;
}

/**
 * Registers theme supports and menu locations.
 */
function d11_setup(): void
{
    d11_load_translations();

    add_theme_support('wp-block-styles');
    add_theme_support('responsive-embeds');
    add_theme_support('editor-styles');
    add_theme_support('automatic-feed-links');
    add_theme_support('post-thumbnails');
    add_editor_style('assets/css/editor.css');

    register_nav_menus([
        'primary' => __('Primary Navigation', 'd11'),
        'footer' => __('Footer Navigation', 'd11'),
    ]);
}
add_action('after_setup_theme', 'd11_setup');

/**
 * Loads the theme translations, supporting the current domain-prefixed MO naming.
 */
function d11_load_translations(): void
{
    $languages_path = d11_languages_path();
    $locale = function_exists('determine_locale') ? determine_locale() : get_locale();
    $domain_mofile = $languages_path . '/d11-' . $locale . '.mo';

    if (file_exists($domain_mofile)) {
        load_textdomain('d11', $domain_mofile);
        return;
    }

    load_theme_textdomain('d11', $languages_path);
}

/**
 * Returns the absolute path to the theme languages directory.
 */
function d11_languages_path(): string
{
    return get_theme_file_path('languages');
}

/**
 * Enqueues the front-end asset bundle generated by Vite.
 */
function d11_enqueue_assets(): void
{
    d11_enqueue_vite_assets();
}
add_action('wp_enqueue_scripts', 'd11_enqueue_assets');

/**
 * Loads editor-only styles so the block editor stays aligned with the front end.
 */
function d11_enqueue_editor_assets(): void
{
    $editor_css = get_theme_file_uri('assets/css/editor.css');
    $editor_path = get_theme_file_path('assets/css/editor.css');
    $version = file_exists($editor_path) ? (string) filemtime($editor_path) : D11_VERSION;

    wp_enqueue_style('d11-editor', $editor_css, [], $version);
}
add_action('enqueue_block_editor_assets', 'd11_enqueue_editor_assets');
