<?php

declare(strict_types=1);

/**
 * Bootstraps the theme and wires together setup, front-end assets, and editor assets.
 */

if (! defined('ABSPATH')) {
    exit;
}

const D11_VERSION = '0.1.1';

require_once get_theme_file_path('inc/assets.php');
require_once get_theme_file_path('inc/blocks.php');
require_once get_theme_file_path('inc/block-styles.php');
require_once get_theme_file_path('inc/patterns.php');

foreach (glob(get_theme_file_path('partials/*.php')) ?: [] as $partial_file) {
    require_once $partial_file;
}

/**
 * Registers theme supports and menu locations.
 */
function d11_setup(): void
{
    d11_load_translations();

    add_theme_support('wp-block-styles');
    add_theme_support('responsive-embeds');
    add_theme_support('editor-styles');
    add_theme_support('automatic-feed-links');
    add_theme_support('post-thumbnails');
    add_editor_style(d11_get_theme_style_relative_path('src/css/editor.css'));

    register_nav_menus([
        'primary' => __('Primary Navigation', 'd11'),
        'footer' => __('Footer Navigation', 'd11'),
    ]);
}
add_action('after_setup_theme', 'd11_setup');

/**
 * Loads the theme translations, supporting the current domain-prefixed MO naming.
 */
function d11_load_translations(): void
{
    $languages_path = d11_languages_path();
    $locale = function_exists('determine_locale') ? determine_locale() : get_locale();
    $domain_mofile = $languages_path . '/d11-' . $locale . '.mo';

    if (file_exists($domain_mofile)) {
        load_textdomain('d11', $domain_mofile);
        return;
    }

    load_theme_textdomain('d11', $languages_path);
}

/**
 * Returns the absolute path to the theme languages directory.
 */
function d11_languages_path(): string
{
    return get_theme_file_path('languages');
}

/**
 * Enqueues the front-end asset bundle generated by Vite.
 */
function d11_enqueue_assets(): void
{
    d11_enqueue_vite_assets();
}
add_action('wp_enqueue_scripts', 'd11_enqueue_assets');

/**
 * Loads editor-only styles so the block editor stays aligned with the front end.
 */
function d11_enqueue_editor_assets(): void
{
    d11_register_vite_style('d11-editor', 'src/css/editor.css');
    wp_enqueue_style('d11-editor');

    if (d11_should_use_vite_dev_server()) {
        $server = untrailingslashit(d11_get_vite_dev_server());

        wp_enqueue_script('d11-vite-client', $server . '/@vite/client', [], null, true);
        wp_enqueue_style('d11-editor-theme', $server . '/src/css/app.css', ['d11-editor'], null);
        return;
    }

    $theme_css_path = d11_get_theme_style_path('src/css/app.css');

    if (! file_exists($theme_css_path)) {
        return;
    }

    $theme_css_uri = d11_get_theme_style_uri('src/css/app.css');
    $theme_css_version = (string) filemtime($theme_css_path);

    wp_enqueue_style('d11-editor-theme', $theme_css_uri, ['d11-editor'], $theme_css_version);
}
add_action('enqueue_block_editor_assets', 'd11_enqueue_editor_assets');
