export default {
  content: [
    './*.php',
    './*.html',
    './content/**/*.json',
    './templates/**/*.html',
    './parts/**/*.html',
    './patterns/**/*.{php,html}',
    './inc/**/*.php',
    './src/js/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        white: '#ffffff',
        black: '#0f172a',
        light: '#f3f7ff',
        primary: '#2563eb',
        accent: '#06b6d4',
        paper: '#f3f7ff',
        sand: '#e0ecff',
        line: '#cbd5e1',
        ink: '#0f172a',
        cinder: '#334155',
        clay: '#64748b',
        sage: '#38bdf8',
        ember: '#2563eb',
        sun: '#06b6d4',
      },
      fontFamily: {
        heading: ['"Space Grotesk"', 'sans-serif'],
        paragraph: ['"Inter"', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'monospace'],
      },
      fontSize: {
        hero: ['clamp(4rem, 9vw, 8rem)', { lineHeight: '0.88', letterSpacing: '-0.03em' }],
        display: ['clamp(2.5rem, 5vw, 4.5rem)', { lineHeight: '0.92', letterSpacing: '-0.02em' }],
        'section-title': ['clamp(1.75rem, 3vw, 3rem)', { lineHeight: '1.1' }],
        lead: ['clamp(1.125rem, 1.4vw, 1.35rem)', { lineHeight: '1.65' }],
        kicker: ['0.72rem', { lineHeight: '1', letterSpacing: '0.22em' }],
        metric: ['clamp(2.1rem, 4vw, 3.5rem)', { lineHeight: '0.95', letterSpacing: '-0.04em' }],
      },
      letterSpacing: {
        tightest: '-0.03em',
        brand: '0.1em',
        wide: '0.14em',
        hero: '-0.04em',
        kicker: '0.22em',
      },
      lineHeight: {
        flat: '0.95',
        body: '1.7',
      },
      spacing: {
        xs: '0.5rem',
        sm: '1rem',
        md: '1.5rem',
        lg: '3rem',
        xl: '5rem',
        '2xl': '6rem',
        '3xl': '8rem',
      },
      maxWidth: {
        content: '48rem',
        wide: '80rem',
      },
      borderRadius: {
        sm: '0.375rem',
        md: '0.75rem',
        lg: '1.5rem',
        xl: '2rem',
        pill: '999px',
        card: '1.5rem',
      },
      boxShadow: {
        card: '0 18px 50px -28px rgb(15 23 42 / 0.18)',
        panel: '0 32px 100px -44px rgb(37 99 235 / 0.28)',
        float: '0 24px 80px -38px rgb(6 182 212 / 0.34)',
      },
    },
  },
  plugins: [],
};
